### ISSUE TITLE
How to Hide Build ID  ?

### ISSUE THREAD

**Issue by sachinsenal0x64** [vvbbnn00/onedrive-index#12]
![image](https://github.com/vvbbnn00/onedrive-index/assets/127573781/74e1dea4-ef0c-4c1d-881c-2e5bc9d680f4)

**Comment by vvbbnn00** [comment]
Hello, you can comment out this line: 

https://github.com/vvbbnn00/onedrive-index/blob/3f53b04ce50feb43cae8b5c662e322c0b510c50c/app/src/components/Footer.tsx#L13C7-L13C50

**Comment by sachinsenal0x64** [comment]
Thanks anyway, way to fix this ?

OneDrive-index 

![image](https://github.com/vvbbnn00/onedrive-index/assets/127573781/3e0c4cdf-e33c-4c51-bf27-4f004bf12aac)

Alist

![image](https://github.com/vvbbnn00/onedrive-index/assets/127573781/b8ba37c2-700d-41a1-b9a1-4fb95618e107)

**Comment by vvbbnn00** [comment]
It seems that there are some issues with the support for Markdown parsing. 
We will look for a solution to fix it later.

**Comment by sachinsenal0x64** [comment]
Ok thanks
